### ISSUE TITLE
feat: animate when switching between pages

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#101]
Please do tell what kind of animation you are planning to implement. Animation should be short and simple

**Comment by titusjoyson** [comment]
@ashuvssut I like to solve this issue

**Comment by ashuvssut** [comment]
Please do tell what kind of animation you are going to implement

**Comment by titusjoyson** [comment]
> What kind of animation have you thought to implement?

Will update before I start, looking into few options. I'll go through the website and try to provide a suitable animation for it.

**Comment by titusjoyson** [comment]
I can see some flickering issue in header when navigating, I'll try to fix that as well

**Comment by ashuvssut** [comment]
Can you fix that first? It would be nice if you could open up a issue and its separate PR that fixes it.

That fix will be merged first

**Comment by titusjoyson** [comment]
@ashuvssut planning to implement linear animation since it will be more simpler. Adding two gifs for refer top to down and left to right animations, Hava a look and let me know your suggestions. And I was using [framer]( https://www.framer.com/docs/transition/) 

![top-down-page-animation](https://user-images.githubusercontent.com/14018471/194708220-f18718d5-67f3-4c24-a178-72950ef89cb2.gif)
![left-right-page-animation](https://user-images.githubusercontent.com/14018471/194708263-ec2766de-9bd6-4a4f-b18c-1733bd202954.gif)

**Comment by ashuvssut** [comment]
Lets go with the first one (top to bottom animation).
